[general]
import = [
    "~/.config/alacritty/ever_forest.toml"
]

[terminal.shell]
program="/bin/zsh"

[window]
opacity=0.95
padding.x=10
padding.y=10

[font]
normal.family = "JetBrains Mono"
size=10.0

